### ISSUE TITLE
java.lang.SecurityException: Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by nekot** [sony/smarttennissensorsdk#1]
Hi,

I can build sample application, but could not launch it, because of this fatal exception caused while launching this app.
I'm using SO-04H (Android 6.0.1) , so I suppose this is caused by Android M runtime permission changes?

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: com.sony.samples.smarttennissensor, PID: 21153
>                   java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.sony.smarttennissensor.sdk.host/com.sony.smarttennissensor.service.AriakeService }

**Comment by sriramsam** [comment]
Hello,

This does work on Android 6.0.1. 

Could you kindly confirm if the Host.apk is installed? You do need to install the Host.apk that you may have received from us after signing the license agreement. If not, you will get the SecurityException as evident from lines 1317-1324 at: http://androidxref.com/6.0.1_r10/xref/frameworks/base/core/java/android/app/ContextImpl.java#bindServiceCommon

**Comment by nekot** [comment]
Yes, I received host.apk and installed using adb.  
How can I confirm it?

**Comment by nekot** [comment]
I tried to run this sample app gain, and now I can successfully do Bind.
But Connect fails many times. Sometimes it succeeds, but most of times failed, and "OnConnectionFailed" is displayed.
How can I display detailed error message of "Connect"?

**Comment by sriramsam** [comment]
Glad that you're able to Bind!

If you have the [Smart Tennis Sensor app](https://play.google.com/store/apps/details?id=com.sony.smarttennissensor) installed on the same device, please refer to section 8 in the [Developers Guide](https://github.com/sony/smarttennissensorsdk/blob/master/SmartTennisSensor_SDK_Developers_Guide.pdf). If the sensor is already connected with the Smart Tennis Sensor app, the Host app will not be able to connect simultaneously. You will need to manually restart the sensor before connecting again from the Host app. To determine if this is the cause, consider temporarily installing the Host and sample app on a device without the Smart Tennis Sensor app. 

"Connect" is simply trying to establish a Bluetooth connection with the sensor. Bluetooth may have its own [pairing problems](http://www.techlicious.com/how-to/how-to-fix-bluetooth-pairing-problems/). The Host app may not be able to know the exact reason for a failure to share with its client--for example, that your sensor is not turned on. 

At the time of connect:

1. The sensors' Bluetooth must be turned on. Blue light on the sensor will blink intermittently. This is **not** the same as pairing mode characterized by the fading blinks as seen in this [video](https://youtu.be/rSxRY2F7B3o?t=1m16s).  
2.  This may be obvious, but Bluetooth on your device must also be enabled.

For more details, please refer to section 6.1 and 6.3.3 from the [Developers Guide](https://github.com/sony/smarttennissensorsdk/blob/master/SmartTennisSensor_SDK_Developers_Guide.pdf). The above are sufficient to be able to consistently "Connect" with the sensor. 

I assumed that you have one sensor and are trying to connect to the same every time. If you have paired multiple sensors, please ensure that the desired sensor is in the correct mode as described above.


Good luck!
